[project]
name = "URL-SHORTNER"
version = "0.1.0"
description = "Building my own url shortner application to learn system design"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.19.1",
    "asyncpg>=0.31.0",
    "fastapi>=0.141.1",
    "pydantic-settings>=2.15.0",
    "sqlalchemy>=2.0.52",
    "uvicorn[standard]>=0.52.3",
]
